### ISSUE TITLE
请问呢这些安装包为什么不加入pyproject.toml里

### ISSUE THREAD

**Issue by fengyunzaidushi** [susirial/Mojuan#2]
`
pip install libmagic (linux)

pip install python-magic-bin (windows)

pip install qianfan

pip install zhipuai

pip install dashscope

pip install elasticsearch

pip install pandas

pip install appbuilder

pip install pydantic[email]

pip install passlib

pip install uvicorn

pip install bcrypt

pip install chromadb

pip install python-magic

`

**Comment by susirial** [comment]
还有些问题~ 有的内容还没实现~
